### ISSUE TITLE
Doesn't seem to work with binary data.

### ISSUE THREAD

**Issue by pkrumins** [brainpicture/node-base64#1]
Try encoding any binary data, produces something different than expected.

**Comment by brainpicture** [comment]
please, tell me how are you work with binary data.. (throw buffer?)

**Comment by pkrumins** [comment]
Hmm, did you get my message? I wrote a really lengthy one in regard to this problem. I somehow can't see it here.

**Comment by pkrumins** [comment]
Found it!

**Comment by pkrumins** [comment]
I actually just wrote a new module that works, and uses different algorithm than yours. Mine does encoding only for now because I don't need decoding.

It's here: http://github.com/pkrumins/node-base64

Here is how your module doesn't work. I am encoding very simply:

```
var base64_encode = require('base64').encode;
var sys = require('sys');
var fs = require('fs');

var data = fs.readFileSync('binaryfile', 'binary');   
fs.writeFileSync('out-base64', base64_encode(data), 'binary');
```

This fails with your module.

Also tried putting data in buffer first, but that doesn't save it from failing:

```
var base64_encode = require('base64').encode;
var sys = require('sys');
var fs = require('fs');
var Buffer = require('buffer').Buffer;

var data = fs.readFileSync('binaryfile', 'binary');   
var dataBuf = new Buffer(data.length);
dataBuf.write(data, 'binary');

fs.writeFileSync('out-base64', base64_encode(dataBuf), 'binary');
```

Here is the Perl program that I use to compare if the results are good:

```
#!/usr/bin/perl

use MIME::Base64 qw(encode_base64);

my $filename = shift || die "no filename";

open(FILE, $filename) or die "$!";
while (read(FILE, $buf, 60*57)) {
    print encode_base64($buf, '');
}
```

You can use my test cases from my module to improve your module! http://github.com/pkrumins/node-base64/tree/master/tests/

(Just run the ./test.sh script from tests/ directory.)

I also know what the problem with your module is -- this line:

```
String::Utf8Value data(args[0]->ToString());
```

in `base64_encode_binding`.

It creates a Utf8 String from binary data - doesn't make any sense.

But there is no easy workaround at the moment, because binary data is not well supported in node.js.

That's why my module only accepts buffers as arguments!

If you find a workaround, please let me know!

**Comment by brainpicture** [comment]
Fixed

**Comment by pkrumins** [comment]
thanks!

**Comment by Errorbot1122** [comment]
👍
