### ISSUE TITLE
Leaking memory

### ISSUE THREAD

**Issue by pkrumins** [brainpicture/node-base64#2]
The other problem in your module is that it's leaking memory in `base64_encode_binding`. See, you are doing this:

```
unsigned char* str=base64_decode((unsigned char*)*data,data.length(),&len);
```

And then you:

```
return String::New((const char*)str,len);
```

But `String::New` constructs a new string from `char *`, it does not copy the pointer internally.

And before this you do:

```
result = (unsigned char *)malloc(length+1);
```

in `base64_decode`.

This pointer leaks!

My suggested fix:

```
Handle<Value>
base64_encode_binding(const Arguments& args)
{
  HandleScope scope;
  String::Utf8Value data(args[0]->ToString());
  int len;
  unsigned char* str=base64_encode((unsigned char*)*data,data.length(),&len);
  Local<String> ret = String::New((const char*)str,len);
  free(str);
  return ret;
}
```

**Comment by brainpicture** [comment]
Thanks very much, I have commited you fix.

**Comment by pkrumins** [comment]
You're welcome! :)

**Comment by pkrumins** [comment]
Oh, same problem in `base64_decode_binding`!
