### ISSUE TITLE
about binary decode

### ISSUE THREAD

**Issue by tdebarochez** [brainpicture/node-base64#3]
I've got strange results with JPEG headers, results are differents with php.

In PHP :
php -r 'file_put_contents("/tmp/blah", base64_decode("/9j/"));'
// hd /tmp/blah => 0xff 0xd8 0xff

In node-repl :
require('fs').writeFileSync('/tmp/blah', require('node-base64').decode('/9j/'),'binary');
// hd /tmp/blah => 0xfd 0xfd 0xfd

Does the problem comes from binary data decoding ?

**Comment by brainpicture** [comment]
Try now please
